name: Spell Checking

on: [pull_request]

jobs:
  codespell:
    name: Check spelling all files with codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install codespell
      - name: Check spelling with codespell
        run: codespell --ignore-words=.codespell.txt || exit 1
  misspell:
    name: Check spelling all files in commit with misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: wget -O - -q https://git.io/misspell | sh -s -- -b .
      - name: Misspell
        run: git ls-files --empty-directory | xargs ./misspell -i 'enviromnent' -error